import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";
import "@/shared/styles/themes.css";
import type { Metadata } from "next";
import { MantineProvider } from "@mantine/core";
import { QueryClientProvider } from "@tanstack/react-query";
import query from "@/shared/libs/query-client";
import { ModalsProvider } from "@mantine/modals";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={query}>
          <MantineProvider>
            <ModalsProvider>{children}</ModalsProvider>
          </MantineProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
